---
# GitHub Actions workflow to lint commits on pull requests of the TerraHarbor repositories.
#
# IMPORTANT: This workflow is called by other workflows in the organization's repositories and it is centralized here 
# in order to be easily maintained. Because of this, please make sure you're not introducing any breaking changes when
# modifying this workflow.

name: "commits-checks"

on:
  workflow_call:
  pull_request:

jobs:
  commits-checks:
    runs-on: ubuntu-latest

    steps:
    - name: Check commit messages
      uses: opensource-nepal/commitlint@v1.3.0
