---
# GitHub Actions workflow to automatically package and publish Docker images for the TerraHarbor organization.
#
# IMPORTANT: This workflow is called by other workflows in the organization's repositories and it is centralized here 
# in order to be easily maintained. Because of this, please make sure you're not introducing any breaking changes when
# modifying this workflow.

name: "docker-build"

on:
  workflow_call:
    inputs:
      build_context:
        description: "The build context for the Docker image"
        type: string
        default: "."
      dockerfile_path:
        description: "The path to the Dockerfile"
        type: string
        default: "Dockerfile"
    secrets:
      TERRAHARBOR_RELEASER_APP_ID:
        description: "App ID of the GitHub app with permissions to create PRs and modify files on the TerraHarbor repositories"
        required: true
      TERRAHARBOR_RELEASER_PRIVATE_KEY:
        description: "PEM private key of the GitHub app with permissions to create PRs and modify files on the TerraHarbor repositories"
        required: true

jobs:
  docker-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [ linux/amd64, linux/arm64 ]

    steps:
    - name: "Checkout the repository"
      uses: actions/checkout@v4

    - name: Generate authentication token from GitHub App
      id: app-token
      uses: actions/create-github-app-token@v2.0.6
      with:
        app-id: ${{ secrets.TERRAHARBOR_RELEASER_APP_ID }}
        private-key: ${{ secrets.TERRAHARBOR_RELEASER_PRIVATE_KEY }}

    - name: "Extract metadata for the Docker image"
      if: github.event_name == 'push' && github.ref_type == 'tag' # Only extract metadata if we push a tag
      id: metadata_extraction
      uses: docker/metadata-action@v5.7.0
      with:
        images: ghcr.io/${{ github.repository }}

    - name: "Login to GitHub Container Registry"
      if: github.event_name == 'push' && github.ref_type == 'tag' # Only login if we push a tag
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ steps.app-token.outputs.token }}

    - name: "Set up Docker Buildx"
      uses: docker/setup-buildx-action@v3.4.0

    - name: "Build and eventually push container image"
      uses: docker/build-push-action@v6.18.0
      with:
        context: ${{ inputs.build_context }}
        file: ${{ inputs.dockerfile_path }}
        platforms: ${{ matrix.platform }}
        tags: ${{ steps.metadata_extraction.outputs.tags }}
        labels: ${{ steps.metadata_extraction.outputs.labels }}
        push: ${{ github.event_name == 'push' && github.ref_type == 'tag' }} # Only push built image if we push a tag
