---
# GitHub Actions workflow to automatically package and publish Docker images for the TerraHarbor organization.
#
# IMPORTANT: This workflow is called by other workflows in the organization's repositories and it is centralized here 
# in order to be easily maintained. Because of this, please make sure you're not introducing any breaking changes when
# modifying this workflow.

name: "docker-build"

on:
  workflow_call:
    inputs:
      push_image:
        description: "Whether to push the Docker image to the registry"
        type: boolean
        required: true
      build_context:
        description: "The build context for the Docker image"
        type: string
        default: "."
      dockerfile_path:
        description: "The path to the Dockerfile"
        type: string
        default: "Dockerfile"
    secrets:
      GITHUB_TOKEN_CALLER:
        description: "GitHub token with permissions to push the Docker image to the registry"
        required: true
      TERRAHARBOR_MAINTAINER_APP_ID:
        description: "App ID of the GitHub app with permissions to add issues and PRs to the TerraHarbor project board"
        required: true
      TERRAHARBOR_MAINTAINER_PRIVATE_KEY:
        description: "PEM private key of the GitHub app with permissions to add issues and PRs to the TerraHarbor project board"
        required: true

jobs:
  docker-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [ linux/amd64, linux/arm64 ]

    steps:
    - name: "Checkout the repository"
      uses: actions/checkout@v4

    - name: "Extract metadata for the Docker image"
      if: inputs.push_image
      id: metadata_extraction
      uses: docker/metadata-action@v5.7.0
      with:
        images: ghcr.io/${{ github.repository }}

    - name: "Login to GitHub Container Registry"
      if: inputs.push_image
      uses: docker/login-action@v3.4.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN_CALLER }}

    - name: "Set up Docker Buildx"
      uses: docker/setup-buildx-action@v3.11.1

    - name: "Build and eventually push container image"
      uses: docker/build-push-action@v6.18.0
      with:
        context: ${{ inputs.build_context }}
        file: ${{ inputs.dockerfile_path }}
        platforms: ${{ matrix.platform }}
        tags: ${{ steps.metadata_extraction.outputs.tags }}
        labels: ${{ steps.metadata_extraction.outputs.labels }}
        push: ${{ inputs.push_image }}


  notify_ansible:
    runs-on: ubuntu-latest
    needs: docker-build
    if: inputs.push_image

    steps:
    - name: Generate authentication token from GitHub App
      if: inputs.push_image
      id: app_token
      uses: actions/create-github-app-token@v2.0.6
      with:
        app-id: ${{ secrets.TERRAHARBOR_MAINTAINER_APP_ID }}
        private-key: ${{ secrets.TERRAHARBOR_MAINTAINER_PRIVATE_KEY }}
        owner: terraharbor

    - name: Dispatch Ansible workflow
      if: inputs.push_image
      uses: peter-evans/repository-dispatch@v3
      with:
        event-type: ansible-docker-apply
        repository: terraharbor/infrastructure
        token: ${{ steps.app_token.outputs.token }}
